version: "3.9"

services:
  db:
    image: postgres:16
    container_name: webhook_pg
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # keeps data when the container restarts

  redis:
    image: redis:7
    container_name: webhook_redis
    ports:
      - "6379:6379"
      
  api:
    build: .
    container_name: webhook_api
    environment:
      # Will matter in Milestone 3, but set now for consistency
      DATABASE_URL: postgresql+psycopg2://postgres:admin@db:5432/postgres
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./src:/code/src         # hot‑reload on save
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      
  worker:
    build: .
    container_name: webhook_worker
    command: poetry run celery -A app.celery_app.celery worker -Q deliver --loglevel=info --concurrency=4
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:admin@db:5432/postgres
      REDIS_URL: redis://redis:6379/0
      REDIS_BACKEND_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis

volumes:
  pgdata:
