version: "3.9"

services:
  db:
    image: postgres:16
    container_name: webhook_pg
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # keeps data when the container restarts

  redis:
    image: redis:7
    container_name: webhook_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
