services:
  - type: web
    name: api
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "8000"                       # Render passes $PORT to the script
      - key: DATABASE_URL
        fromDatabase:
          name: webhook-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: webhook-redis
          type: redis
          property: connectionString

  - type: redis
    name: webhook-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0

databases:
  - name: webhook-db
    plan: free
    postgresMajorVersion: "16"
