services:
  # 🔹 FastAPI main app
  - type: web
    name: api
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "8000"
      - key: DATABASE_URL
        fromDatabase:
          name: webhook-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: webhook-redis
          type: redis
          property: connectionString

  # 🔹 Alembic migrations worker — runs on every deploy and exits
  - type: worker
    name: migrate
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile.migrate
    # runCommand: ""            # REQUIRED — tells Render to use CMD
    # autoDeploy: true          # Runs on every push
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: webhook-db
          property: connectionString

  # 🔹 Redis backend
  - type: redis
    name: webhook-redis
    plan: free
    ipAllowList: []           # secure default

databases:
  - name: webhook-db
    plan: free
    postgresMajorVersion: "16"
